# docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_gestortareas
    environment:
      POSTGRES_DB: gestor_tareas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: app_gestortareas
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestor_tareas
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    command: ["java", "-jar", "/app.jar"]

volumes:
  postgres_data: